name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: blog-cms/backend/BlogCms.Api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog-cms/frontend/blog-cms-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Build
        env:
          VITE_API_BASE_URL: http://localhost:5073
        run: npm run build
